### ISSUE TITLE
gcache page files not deleted

### ISSUE THREAD

**Issue by jesusch** [codership/galera#229]
hi,

env:

3 node debian wheezy
percona xtradb cluster 5.6.21-25.8-938.wheezy
galera: 3.8.3390.wheezy

most of the data produced is imported via mysqlimport aka `load data infile`
all write requests are handled by a single node.
this node is leaking diskspace due to the fact that wsrep is creating a lot of gcache.page.xyz files:

2015-02-12 14:12:04 3445 [Note] WSREP: Created page /var/lib/mysql/gcache.page.002951 of size 134217728 bytes
2015-02-12 14:14:40 3445 [Note] WSREP: Created page /var/lib/mysql/gcache.page.002952 of size 134217728 bytes
2015-02-12 14:20:53 3445 [Note] WSREP: Created page /var/lib/mysql/gcache.page.002953 of size 134217728 bytes

but it is not deleting any of those files.

see also:
http://goo.gl/OPzHVk
https://mariadb.atlassian.net/browse/MDEV-6822

Cheers
B

**Comment by ayurchen** [comment]
Hi, could you try it with Galera 3.9 (http://galeracluster.com/downloads/). It fixes one fragmentation bug that could have effect on this.

**Comment by jesusch** [comment]
Hi, I've used 25.3.9 on all three nodes -> let's see what happens. 
I'll be back.

**Comment by jesusch** [comment]
up until now it seems to be fixed.
I only get sometimes (~2-3 / day) the following error:
2015-02-13 16:11:21 10215 [Warning] WSREP: Failed to report last committed 59800338, -4 (Interrupted system call)

**Comment by ayurchen** [comment]
Great to hear that. The warning message does not seem to be related to the page leak, not directly at least. As long as it's a warning, it is not critical, but it may indicate some resource/system configuration problem on a node. Also, IF 3.9 fixes the bug for you, then most likely this bug was causing data inconsistency between the master and slaves. In this case resyncing slaves with master via full SST may be necessary.

**Comment by jesusch** [comment]
I'm closing this as it seems fixed with 3.9

**Comment by ayurchen** [comment]
This is far from over. 3.9 might have improved something, but I'm still getting this sometimes. Initial investigation shows that there are some unreleased and unordered buffers (meaning just allocated and then abandoned) in the RB store which clog it and make impossible further allocations there.
Now the question is what's in there and why those buffers were abandoned without releasing.
Likewise such unreleased buffers in page store would block deletion of subsequent pages and that will cause running out of disk space.
The leak is likely caused by resetting defragmenter on configuration change.

**Comment by ayurchen** [comment]
reopen was due to false alarm.
